/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.dpi.web.bean;

import java.math.BigDecimal;

import it.eng.dpi.bean.CompareBean;
import it.eng.spagoLite.db.base.JEEBaseRowInterface;
import it.eng.spagoLite.db.base.row.BaseRow;
import it.eng.spagoLite.db.oracle.bean.column.TableDescriptor;

/**
 * RowBean per la tabella Confronti_Pacs
 * 
 */
public class ConfrontiPacsRowBean extends BaseRow implements JEEBaseRowInterface {

    /*
     * @Generated( value = "it.eg.dbtool.db.oracle.beangen.Oracle4JPAClientBeanGen$ViewBeanWriter", comments =
     * "This class was generated by OraTool", date = "Monday, 7 January 2013 15:31" )
     */

    /**
     * 
     */
    private static final long serialVersionUID = -7283200672374881293L;
    public static ConfrontiPacsTableDescriptor TABLE_DESCRIPTOR = new ConfrontiPacsTableDescriptor();

    public ConfrontiPacsRowBean() {
        super();
    }

    public TableDescriptor getTableDescriptor() {
        return TABLE_DESCRIPTOR;
    }

    public BigDecimal getNumStudyPing() {
        return getBigDecimal("num_study_ping");
    }

    public void setNumStudyPing(BigDecimal num_study_ping) {
        setObject("num_study_ping", num_study_ping);
    }

    public BigDecimal getNumStudyPacs() {
        return getBigDecimal("num_study_pacs");
    }

    public void setNumStudyPacs(BigDecimal num_study_pacs) {
        setObject("num_study_pacs", num_study_pacs);
    }

    public BigDecimal getNumStudyDaTrasferire() {
        return getBigDecimal("num_study_da_trasferire");
    }

    public void setNumStudyDaTrasferire(BigDecimal num_study_da_trasferire) {
        setObject("num_study_da_trasferire", num_study_da_trasferire);
    }

    public String getPacsAet() {
        return getString("pacs_aet");
    }

    public void setPacsAet(String pacs_aet) {
        setObject("pacs_aet", pacs_aet);
    }

    @Override
    public void entityToRowBean(Object obj) {
        CompareBean entity = (CompareBean) obj;
        this.setNumStudyPing(new BigDecimal(entity.getNumStudyPing()));
        this.setNumStudyPacs(new BigDecimal(entity.getNumStudyPacs()));
        this.setNumStudyDaTrasferire(new BigDecimal(entity.getNumStudyDaTrasferire()));
        this.setPacsAet(entity.getPacsAet());
    }

    @Override
    public CompareBean rowBeanToEntity() {
        CompareBean entity = new CompareBean();
        entity.setNumStudyPing(this.getNumStudyPing().intValue());
        entity.setNumStudyPacs(this.getNumStudyPacs().intValue());
        entity.setNumStudyDaTrasferire(this.getNumStudyDaTrasferire().intValue());
        entity.setPacsAet(this.getPacsAet());
        return entity;
    }

    // gestione della paginazione
    public void setRownum(Integer rownum) {
        setObject("rownum", rownum);
    }

    public Integer getRownum() {
        return Integer.parseInt(getObject("rownum").toString());
    }

    public void setRnum(Integer rnum) {
        setObject("rnum", rnum);
    }

    public Integer getRnum() {
        return Integer.parseInt(getObject("rnum").toString());
    }

    public void setNumrecords(Integer numRecords) {
        setObject("numrecords", numRecords);
    }

    public Integer getNumrecords() {
        return Integer.parseInt(getObject("numrecords").toString());
    }

}
