/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.dpi.web.bean;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.GregorianCalendar;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;

import it.eng.spagoLite.db.base.JEEBaseRowInterface;
import it.eng.spagoLite.db.base.row.BaseRow;
import it.eng.spagoLite.db.oracle.bean.column.TableDescriptor;

/**
 * RowBean per la tabella Pig_V_Ric_Recup
 *
 */
public class PigVRicRecupRowBean extends BaseRow implements JEEBaseRowInterface {

    /*
     * @Generated( value = "it.eg.dbtool.db.oracle.beangen.Oracle4JPAClientBeanGen$ViewBeanWriter", comments =
     * "This class was generated by OraTool", date = "Thursday, 24 January 2013 17:54" )
     */

    private static final long serialVersionUID = 6403688971149405839L;
    public static PigVRicRecupTableDescriptor TABLE_DESCRIPTOR = new PigVRicRecupTableDescriptor();

    public PigVRicRecupRowBean() {
        super();
    }

    public TableDescriptor getTableDescriptor() {
        return TABLE_DESCRIPTOR;
    }

    public BigDecimal getIdObject() {
        return getBigDecimal("id_object");
    }

    public void setIdObject(BigDecimal id_object) {
        setObject("id_object", id_object);
    }

    public String getCdKeyObject() {
        return getString("cd_key_object");
    }

    public void setCdKeyObject(String cd_key_object) {
        setObject("cd_key_object", cd_key_object);
    }

    public String getTiStatoSessione() {
        return getString("ti_stato_sessione");
    }

    public void setTiStatoSessione(String ti_stato_sessione) {
        setObject("ti_stato_sessione", ti_stato_sessione);
    }

    public Timestamp getDtAperturaSessione() {
        return getTimestamp("dt_apertura_sessione");
    }

    public void setDtAperturaSessione(Timestamp dt_apertura_sessione) {
        setObject("dt_apertura_sessione", dt_apertura_sessione);
    }

    public Timestamp getDtChiusuraSessione() {
        return getTimestamp("dt_chiusura_sessione");
    }

    public void setDtChiusuraSessione(Timestamp dt_chiusura_sessione) {
        setObject("dt_chiusura_sessione", dt_chiusura_sessione);
    }

    public BigDecimal getIdSessione() {
        return getBigDecimal("id_sessione");
    }

    public void setIdSessione(BigDecimal id_sessione) {
        setObject("id_sessione", id_sessione);
    }

    public String getCdErr() {
        return getString("cd_err");
    }

    public void setCdErr(String cd_err) {
        setObject("cd_err", cd_err);
    }

    public String getDlErr() {
        return getString("dl_err");
    }

    public void setDlErr(String dl_err) {
        setObject("dl_err", dl_err);
    }

    public String getChiaveUnitaDoc() {
        return getString("chiave_unita_doc");
    }

    public void setChiaveUnitaDoc(String chiave_unita_doc) {
        setObject("chiave_unita_doc", chiave_unita_doc);
    }

    public String getCdAetNodoDicom() {
        return getString("cd_aet_nodo_dicom");
    }

    public void setCdAetNodoDicom(String cd_aet_nodo_dicom) {
        setObject("cd_aet_nodo_dicom", cd_aet_nodo_dicom);
    }

    public Timestamp getDtStudyDate() {
        return getTimestamp("dt_study_date");
    }

    public void setDtStudyDate(Timestamp dt_study_date) {
        setObject("dt_study_date", dt_study_date);
    }

    public String getDsAccessionNumber() {
        return getString("ds_accession_number");
    }

    public void setDsAccessionNumber(String ds_accession_number) {
        setObject("ds_accession_number", ds_accession_number);
    }

    public String getDsPatientName() {
        return getString("ds_patient_name");
    }

    public void setDsPatientName(String ds_patient_name) {
        setObject("ds_patient_name", ds_patient_name);
    }

    public String getTiPatientSex() {
        return getString("ti_patient_sex");
    }

    public void setTiPatientSex(String ti_patient_sex) {
        setObject("ti_patient_sex", ti_patient_sex);
    }

    public Timestamp getDtPatientBirthDate() {
        return getTimestamp("dt_patient_birth_date");
    }

    public void setDtPatientBirthDate(Timestamp dt_patient_birth_date) {
        setObject("dt_patient_birth_date", dt_patient_birth_date);
    }

    public String getCdPatientId() {
        return getString("cd_patient_id");
    }

    public void setCdPatientId(String cd_patient_id) {
        setObject("cd_patient_id", cd_patient_id);
    }

    public String getCdPatientIdIssuer() {
        return getString("cd_patient_id_issuer");
    }

    public void setCdPatientIdIssuer(String cd_patient_id_issuer) {
        setObject("cd_patient_id_issuer", cd_patient_id_issuer);
    }

    public String getDsRefPhysicianName() {
        return getString("ds_ref_physician_name");
    }

    public void setDsRefPhysicianName(String ds_ref_physician_name) {
        setObject("ds_ref_physician_name", ds_ref_physician_name);
    }

    public String getDlListaModalityInStudy() {
        return getString("dl_lista_modality_in_study");
    }

    public void setDlListaModalityInStudy(String dl_lista_modality_in_study) {
        setObject("dl_lista_modality_in_study", dl_lista_modality_in_study);
    }

    @Override
    public void entityToRowBean(Object obj) {
        RicRecupObjToRowBean entity = (RicRecupObjToRowBean) obj;
        this.setIdObject(new BigDecimal(entity.getOgg().getIdObject()));
        this.setCdKeyObject(entity.getOgg().getCdKeyObject());
        this.setTiStatoSessione(entity.getOgg().getTiStatoSessione());
        if (entity.getOgg().getDtAperturaSessione() != null) {
            this.setDtAperturaSessione(
                    new Timestamp(entity.getOgg().getDtAperturaSessione().toGregorianCalendar().getTimeInMillis()));
        }
        if (entity.getOgg().getDtChiusuraSessione() != null) {
            this.setDtChiusuraSessione(
                    new Timestamp(entity.getOgg().getDtChiusuraSessione().toGregorianCalendar().getTimeInMillis()));
        }
        this.setIdSessione(new BigDecimal(entity.getOgg().getIdSessione()));
        this.setCdErr(entity.getOgg().getCdErr());
        this.setDlErr(entity.getOgg().getDsErr());
        this.setChiaveUnitaDoc(entity.getOgg().getChiaveUnitaDoc());
        this.setCdAetNodoDicom(entity.getCdAetNodoDicom());
        if (entity.getDtStudyDate() != null) {
            this.setDtStudyDate(new Timestamp(entity.getDtStudyDate().getTime()));
        }
        this.setDsAccessionNumber(entity.getDsAccessionNumber());
        this.setDsPatientName(entity.getDsPatientName());
        this.setTiPatientSex(entity.getTiPatientSex());
        if (entity.getDtPatientBirthDate() != null) {
            this.setDtPatientBirthDate(new Timestamp(entity.getDtPatientBirthDate().getTime()));
        }
        this.setCdPatientId(entity.getCdPatientId());
        this.setCdPatientIdIssuer(entity.getCdPatientIdIssuer());
        this.setDsRefPhysicianName(entity.getDsRefPhysicianName());
        this.setDlListaModalityInStudy(entity.getDlListaModalityInStudy());
    }

    @Override
    public RicRecupObjToRowBean rowBeanToEntity() {
        RicRecupObjToRowBean entity = new RicRecupObjToRowBean();
        GregorianCalendar cal = new GregorianCalendar();
        DatatypeFactory factory = null;
        try {
            factory = DatatypeFactory.newInstance();
        } catch (DatatypeConfigurationException e) {
        }
        entity.getOgg().setIdObject(this.getIdObject().longValue());
        entity.getOgg().setCdKeyObject(this.getCdKeyObject());
        entity.getOgg().setTiStatoSessione(this.getTiStatoSessione());
        if (this.getDtAperturaSessione() != null) {
            cal.setTime(this.getDtAperturaSessione());
            entity.getOgg().setDtAperturaSessione(factory.newXMLGregorianCalendar(cal));
        } else {
            entity.getOgg().setDtAperturaSessione(null);
        }
        if (this.getDtChiusuraSessione() != null) {
            cal.setTime(this.getDtChiusuraSessione());
            entity.getOgg().setDtChiusuraSessione(factory.newXMLGregorianCalendar(cal));
        } else {
            entity.getOgg().setDtChiusuraSessione(null);
        }
        entity.getOgg().setIdSessione(this.getIdSessione().longValue());
        entity.getOgg().setCdErr(this.getCdErr());
        entity.getOgg().setDsErr(this.getDlErr());
        entity.getOgg().setChiaveUnitaDoc(this.getChiaveUnitaDoc());
        entity.setCdAetNodoDicom(this.getCdAetNodoDicom());
        entity.setDtStudyDate(this.getDtStudyDate());
        entity.setDsAccessionNumber(this.getDsAccessionNumber());
        entity.setDsPatientName(this.getDsPatientName());
        entity.setTiPatientSex(this.getTiPatientSex());
        entity.setDtPatientBirthDate(this.getDtPatientBirthDate());
        entity.setCdPatientId(this.getCdPatientId());
        entity.setCdPatientIdIssuer(this.getCdPatientIdIssuer());
        entity.setDsRefPhysicianName(this.getDsRefPhysicianName());
        entity.setDlListaModalityInStudy(this.getDlListaModalityInStudy());
        return entity;
    }

    // gestione della paginazione
    public void setRownum(Integer rownum) {
        setObject("rownum", rownum);
    }

    public Integer getRownum() {
        return Integer.parseInt(getObject("rownum").toString());
    }

    public void setRnum(Integer rnum) {
        setObject("rnum", rnum);
    }

    public Integer getRnum() {
        return Integer.parseInt(getObject("rnum").toString());
    }

    public void setNumrecords(Integer numRecords) {
        setObject("numrecords", numRecords);
    }

    public Integer getNumrecords() {
        return Integer.parseInt(getObject("numrecords").toString());
    }

}
