/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.dpi.web.bean;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.GregorianCalendar;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;

import it.eng.dpi.web.util.Constants;
import it.eng.spagoLite.db.base.JEEBaseRowInterface;
import it.eng.spagoLite.db.base.row.BaseRow;
import it.eng.spagoLite.db.oracle.bean.column.TableDescriptor;

/**
 * RowBean per la tabella Pig_V_Ric_Diario
 * 
 */
public class PigVRicDiarioRowBean extends BaseRow implements JEEBaseRowInterface {

    /*
     * @Generated( value = "it.eg.dbtool.db.oracle.beangen.Oracle4JPAClientBeanGen$ViewBeanWriter", comments =
     * "This class was generated by OraTool", date = "Monday, 7 January 2013 15:31" )
     */

    /**
     * 
     */
    private static final long serialVersionUID = -7283200672374881293L;
    public static PigVRicDiarioTableDescriptor TABLE_DESCRIPTOR = new PigVRicDiarioTableDescriptor();

    public PigVRicDiarioRowBean() {
        super();
    }

    public TableDescriptor getTableDescriptor() {
        return TABLE_DESCRIPTOR;
    }

    public BigDecimal getIdObject() {
        return getBigDecimal("id_object");
    }

    public void setIdObject(BigDecimal id_object) {
        setObject("id_object", id_object);
    }

    public String getCdKeyObject() {
        return getString("cd_key_object");
    }

    public void setCdKeyObject(String cd_key_object) {
        setObject("cd_key_object", cd_key_object);
    }

    public String getTiStatoObject() {
        return getString("ti_stato_object");
    }

    public void setTiStatoObject(String ti_stato_object) {
        setObject("ti_stato_object", ti_stato_object);
    }

    public String getTiStatoSessione() {
        return getString("ti_stato_sessione");
    }

    public void setTiStatoSessione(String ti_stato_sessione) {
        setObject("ti_stato_sessione", ti_stato_sessione);
    }

    public Timestamp getDtAperturaSessione() {
        return getTimestamp("dt_apertura_sessione");
    }

    public void setDtAperturaSessione(Timestamp dt_apertura_sessione) {
        setObject("dt_apertura_sessione", dt_apertura_sessione);
    }

    public Timestamp getDtChiusuraSessione() {
        return getTimestamp("dt_chiusura_sessione");
    }

    public void setDtChiusuraSessione(Timestamp dt_chiusura_sessione) {
        setObject("dt_chiusura_sessione", dt_chiusura_sessione);
    }

    public BigDecimal getIdSessione() {
        return getBigDecimal("id_sessione");
    }

    public void setIdSessione(BigDecimal id_sessione) {
        setObject("id_sessione", id_sessione);
    }

    public String getFlForzaAccettazione() {
        return getString("fl_forza_accettazione");
    }

    public void setFlForzaAccettazione(String fl_forza_accettazione) {
        setObject("fl_forza_accettazione", fl_forza_accettazione);
    }

    public String getDlMotivoForzaAccettazione() {
        return getString("dl_motivo_forza_accettazione");
    }

    public void setDlMotivoForzaAccettazione(String dl_motivo_forza_accettazione) {
        setObject("dl_motivo_forza_accettazione", dl_motivo_forza_accettazione);
    }

    public String getFlForzaWarning() {
        return getString("fl_forza_warning");
    }

    public void setFlForzaWarning(String fl_forza_warning) {
        setObject("fl_forza_warning", fl_forza_warning);
    }

    public String getDlMotivoChiusoWarning() {
        return getString("dl_motivo_chiuso_warning");
    }

    public void setDlMotivoChiusoWarning(String dl_motivo_chiuso_warning) {
        setObject("dl_motivo_chiuso_warning", dl_motivo_chiuso_warning);
    }

    public String getCdErr() {
        return getString("cd_err");
    }

    public void setCdErr(String cd_err) {
        setObject("cd_err", cd_err);
    }

    public String getDlErr() {
        return getString("dl_err");
    }

    public void setDlErr(String dl_err) {
        setObject("dl_err", dl_err);
    }

    public String getTiStatoSessioneRecup() {
        return getString("ti_stato_sessione_recup");
    }

    public void setTiStatoSessioneRecup(String ti_stato_sessione_recup) {
        setObject("ti_stato_sessione_recup", ti_stato_sessione_recup);
    }

    public Timestamp getDtAperturaSessioneRecup() {
        return getTimestamp("dt_apertura_sessione_recup");
    }

    public void setDtAperturaSessioneRecup(Timestamp dt_apertura_sessione_recup) {
        setObject("dt_apertura_sessione_recup", dt_apertura_sessione_recup);
    }

    public String getChiaveUnitaDoc() {
        return getString("chiave_unita_doc");
    }

    public void setChiaveUnitaDoc(String chiave_unita_doc) {
        setObject("chiave_unita_doc", chiave_unita_doc);
    }

    public String getCdAetNodoDicom() {
        return getString("cd_aet_nodo_dicom");
    }

    public void setCdAetNodoDicom(String cd_aet_nodo_dicom) {
        setObject("cd_aet_nodo_dicom", cd_aet_nodo_dicom);
    }

    public Timestamp getDtStudyDate() {
        return getTimestamp("dt_study_date");
    }

    public void setDtStudyDate(Timestamp dt_study_date) {
        setObject("dt_study_date", dt_study_date);
    }

    public String getDsAccessionNumber() {
        return getString("ds_accession_number");
    }

    public void setDsAccessionNumber(String ds_accession_number) {
        setObject("ds_accession_number", ds_accession_number);
    }

    public String getDsPatientName() {
        return getString("ds_patient_name");
    }

    public void setDsPatientName(String ds_patient_name) {
        setObject("ds_patient_name", ds_patient_name);
    }

    public String getTiPatientSex() {
        return getString("ti_patient_sex");
    }

    public void setTiPatientSex(String ti_patient_sex) {
        setObject("ti_patient_sex", ti_patient_sex);
    }

    public Timestamp getDtPatientBirthDate() {
        return getTimestamp("dt_patient_birth_date");
    }

    public void setDtPatientBirthDate(Timestamp dt_patient_birth_date) {
        setObject("dt_patient_birth_date", dt_patient_birth_date);
    }

    public String getCdPatientId() {
        return getString("cd_patient_id");
    }

    public void setCdPatientId(String cd_patient_id) {
        setObject("cd_patient_id", cd_patient_id);
    }

    public String getCdPatientIdIssuer() {
        return getString("cd_patient_id_issuer");
    }

    public void setCdPatientIdIssuer(String cd_patient_id_issuer) {
        setObject("cd_patient_id_issuer", cd_patient_id_issuer);
    }

    public String getDsRefPhysicianName() {
        return getString("ds_ref_physician_name");
    }

    public void setDsRefPhysicianName(String ds_ref_physician_name) {
        setObject("ds_ref_physician_name", ds_ref_physician_name);
    }

    public String getDlListaModalityInStudy() {
        return getString("dl_lista_modality_in_study");
    }

    public void setDlListaModalityInStudy(String dl_lista_modality_in_study) {
        setObject("dl_lista_modality_in_study", dl_lista_modality_in_study);
    }

    public String getDlListaSopClass() {
        return getString("dl_lista_sop_class");
    }

    public void setDlListaSopClass(String dl_lista_sop_class) {
        setObject("dl_lista_sop_class", dl_lista_sop_class);
    }

    public String getDsInstitutionName() {
        return getString("ds_institution_name");
    }

    public void setDsInstitutionName(String ds_institution_name) {
        setObject("ds_institution_name", ds_institution_name);
    }

    public String getDlStudyDescription() {
        return getString("dl_study_description");
    }

    public void setDlStudyDescription(String dl_study_description) {
        setObject("dl_study_description", dl_study_description);
    }

    public String getDsStudyInstanceUid() {
        return getString("ds_study_instance_uid");
    }

    public void setDsStudyInstanceUid(String ds_study_instance_uid) {
        setObject("ds_study_instance_uid", ds_study_instance_uid);
    }

    public BigDecimal getNiStudyRelatedSeries() {
        return getBigDecimal("ni_study_related_series");
    }

    public void setNiStudyRelatedSeries(BigDecimal ni_study_related_series) {
        setObject("ni_study_related_series", ni_study_related_series);
    }

    public BigDecimal getNiStudyRelatedImages() {
        return getBigDecimal("ni_study_related_images");
    }

    public void setNiStudyRelatedImages(BigDecimal ni_study_related_images) {
        setObject("ni_study_related_images", ni_study_related_images);
    }

    public String getDsStudyId() {
        return getString("ds_study_id");
    }

    public void setDsStudyId(String ds_study_id) {
        setObject("ds_study_id", ds_study_id);
    }

    public Timestamp getDtPresaInCarico() {
        return getTimestamp("dt_presa_in_carico");
    }

    public void setDtPresaInCarico(Timestamp dt_presa_in_carico) {
        setObject("dt_presa_in_carico", dt_presa_in_carico);
    }

    public String getBlDcmHashTxt() {
        return getString("bl_dcm_hash_txt");
    }

    public void setBlDcmHashTxt(String bl_dcm_hash_txt) {
        setObject("bl_dcm_hash_txt", bl_dcm_hash_txt);
    }

    public String getDsDcmHash() {
        return getString("ds_dcm_hash");
    }

    public void setDsDcmHash(String ds_dcm_hash) {
        setObject("ds_dcm_hash", ds_dcm_hash);
    }

    public String getTiAlgoDcmHash() {
        return getString("ti_algo_dcm_hash");
    }

    public void setTiAlgoDcmHash(String ti_algo_dcm_hash) {
        setObject("ti_algo_dcm_hash", ti_algo_dcm_hash);
    }

    public String getCdEncodingDcmHash() {
        return getString("cd_encoding_dcm_hash");
    }

    public void setCdEncodingDcmHash(String cd_encoding_dcm_hash) {
        setObject("cd_encoding_dcm_hash", cd_encoding_dcm_hash);
    }

    public String getBlGlobalHashTxt() {
        return getString("bl_global_hash_txt");
    }

    public void setBlGlobalHashTxt(String bl_global_hash_txt) {
        setObject("bl_global_hash_txt", bl_global_hash_txt);
    }

    public String getDsGlobalHash() {
        return getString("ds_global_hash");
    }

    public void setDsGlobalHash(String ds_global_hash) {
        setObject("ds_global_hash", ds_global_hash);
    }

    public String getTiAlgoGlobalHash() {
        return getString("ti_algo_global_hash");
    }

    public void setTiAlgoGlobalHash(String ti_algo_global_hash) {
        setObject("ti_algo_global_hash", ti_algo_global_hash);
    }

    public String getCdEncodingGlobalHash() {
        return getString("cd_encoding_global_hash");
    }

    public void setCdEncodingGlobalHash(String cd_encoding_global_hash) {
        setObject("cd_encoding_global_hash", cd_encoding_global_hash);
    }

    public String getDsFileHash() {
        return getString("ds_file_hash");
    }

    public void setDsFileHash(String ds_file_hash) {
        setObject("ds_file_hash", ds_file_hash);
    }

    public String getTiAlgoFileHash() {
        return getString("ti_algo_file_hash");
    }

    public void setTiAlgoFileHash(String ti_algo_file_hash) {
        setObject("ti_algo_file_hash", ti_algo_file_hash);
    }

    public String getCdEncodingFileHash() {
        return getString("cd_encoding_file_hash");
    }

    public void setCdEncodingFileHash(String cd_encoding_file_hash) {
        setObject("cd_encoding_file_hash", cd_encoding_file_hash);
    }

    /*
     * ************************************************************** ******************* CAMPI NON GENERATI
     * *********************** *************** MA CREATI PER IL DETTAGLIO *******************
     * **************************************************************
     */
    public String getFlTransferDicom() {
        return getString("fl_transfer_dicom");
    }

    public void setFlTransferDicom(String fl_transfer_dicom) {
        setObject("fl_transfer_dicom", fl_transfer_dicom);
    }

    public String getBlXmlIndiceUd() {
        return getString("bl_xml_indice_ud");
    }

    public void setBlXmlIndiceUd(String bl_xml_indice_ud) {
        setObject("bl_xml_indice_ud", bl_xml_indice_ud);
    }

    public String getBlXmlIndicePc() {
        return getString("bl_xml_indice_pc");
    }

    public void setBlXmlIndicePc(String bl_xml_indice_pc) {
        setObject("bl_xml_indice_pc", bl_xml_indice_pc);
    }

    /* ************************************************************ */

    @Override
    public void entityToRowBean(Object obj) {
        RicDiarioObjToRowBean entity = (RicDiarioObjToRowBean) obj;
        this.setIdObject(entity.getOgg().getIdObject() != null ? new BigDecimal(entity.getOgg().getIdObject()) : null);
        this.setCdKeyObject(entity.getOgg().getCdKeyObject());
        this.setTiStatoObject(entity.getOgg().getTiStatoObject());
        this.setTiStatoSessione(entity.getOgg().getTiStatoSessione());
        if (entity.getOgg().getDtAperturaSessione() != null) {
            this.setDtAperturaSessione(
                    new Timestamp(entity.getOgg().getDtAperturaSessione().toGregorianCalendar().getTimeInMillis()));
        }
        if (entity.getOgg().getDtChiusuraSessione() != null) {
            this.setDtChiusuraSessione(
                    new Timestamp(entity.getOgg().getDtChiusuraSessione().toGregorianCalendar().getTimeInMillis()));
        }
        this.setIdSessione(
                entity.getOgg().getIdSessione() != null ? new BigDecimal(entity.getOgg().getIdSessione()) : null);
        this.setFlForzaAccettazione(entity.getOgg().isFlForzaAccettazione() ? Constants.DB_TRUE : Constants.DB_FALSE);
        this.setDlMotivoForzaAccettazione(entity.getOgg().getDlMotivoForzaAccettazione());
        this.setFlForzaWarning(entity.getOgg().isFlForzaWarning() ? Constants.DB_TRUE : Constants.DB_FALSE);
        this.setDlMotivoChiusoWarning(entity.getOgg().getDlMotivoChiusoWarning());
        this.setCdErr(entity.getOgg().getCdErr());
        this.setDlErr(entity.getOgg().getDsErr());
        this.setTiStatoSessioneRecup(entity.getOgg().getTiStatoSessioneRecup());
        if (entity.getOgg().getDtAperturaSessioneRecup() != null) {
            this.setDtAperturaSessioneRecup(new Timestamp(
                    entity.getOgg().getDtAperturaSessioneRecup().toGregorianCalendar().getTimeInMillis()));
        }
        this.setChiaveUnitaDoc(entity.getOgg().getChiaveUnitaDoc());
        this.setCdAetNodoDicom(entity.getCdAetNodoDicom());
        if (entity.getDtStudyDate() != null) {
            this.setDtStudyDate(new Timestamp(entity.getDtStudyDate().getTime()));
        }
        this.setDsAccessionNumber(entity.getDsAccessionNumber());
        this.setDsPatientName(entity.getDsPatientName());
        this.setTiPatientSex(entity.getTiPatientSex());
        if (entity.getDtPatientBirthDate() != null) {
            this.setDtPatientBirthDate(new Timestamp(entity.getDtPatientBirthDate().getTime()));
        }
        this.setCdPatientId(entity.getCdPatientId());
        this.setCdPatientIdIssuer(entity.getCdPatientIdIssuer());
        this.setDsRefPhysicianName(entity.getDsRefPhysicianName());
        this.setDlListaModalityInStudy(entity.getDlListaModalityInStudy());
        this.setDlListaSopClass(entity.getDlListaSopClass());
        this.setDsInstitutionName(entity.getDsInstitutionName());
        this.setDlStudyDescription(entity.getDlStudyDescription());
        this.setDsStudyInstanceUid(entity.getDsStudyInstanceUid());
        this.setNiStudyRelatedSeries(entity.getNiStudyRelatedSeries());
        this.setNiStudyRelatedImages(entity.getNiStudyRelatedImages());
        this.setDsStudyId(entity.getDsStudyId());
        if (entity.getDtPresaInCarico() != null) {
            this.setDtPresaInCarico(new Timestamp(entity.getDtPresaInCarico().getTime()));
        }
        this.setBlDcmHashTxt(entity.getBlDcmHashTxt());
        this.setDsDcmHash(entity.getDsDcmHash());
        this.setTiAlgoDcmHash(entity.getTiAlgoDcmHash());
        this.setCdEncodingDcmHash(entity.getCdEncodingDcmHash());
        this.setBlGlobalHashTxt(entity.getBlGlobalHashTxt());
        this.setDsGlobalHash(entity.getDsGlobalHash());
        this.setTiAlgoGlobalHash(entity.getTiAlgoGlobalHash());
        this.setCdEncodingGlobalHash(entity.getCdEncodingGlobalHash());
        this.setDsFileHash(entity.getDsFileHash());
        this.setTiAlgoFileHash(entity.getTiAlgoFileHash());
        this.setCdEncodingFileHash(entity.getCdEncodingFileHash());
    }

    @Override
    public RicDiarioObjToRowBean rowBeanToEntity() {
        RicDiarioObjToRowBean entity = new RicDiarioObjToRowBean();
        GregorianCalendar cal = new GregorianCalendar();
        DatatypeFactory factory = null;
        try {
            factory = DatatypeFactory.newInstance();
        } catch (DatatypeConfigurationException e) {
        }

        entity.getOgg().setIdObject(this.getIdObject().longValue());
        entity.getOgg().setCdKeyObject(this.getCdKeyObject());
        entity.getOgg().setTiStatoObject(this.getTiStatoObject());
        entity.getOgg().setTiStatoSessione(this.getTiStatoSessione());

        if (this.getDtAperturaSessione() != null) {
            cal.setTime(this.getDtAperturaSessione());
            entity.getOgg().setDtAperturaSessione(factory.newXMLGregorianCalendar(cal));
        } else {
            entity.getOgg().setDtAperturaSessione(null);
        }
        if (this.getDtChiusuraSessione() != null) {
            cal.setTime(this.getDtChiusuraSessione());
            entity.getOgg().setDtChiusuraSessione(factory.newXMLGregorianCalendar(cal));
        } else {
            entity.getOgg().setDtChiusuraSessione(null);
        }
        entity.getOgg().setIdSessione(this.getIdSessione().longValue());
        entity.getOgg().setFlForzaAccettazione(this.getFlForzaAccettazione().equals(Constants.DB_TRUE));
        entity.getOgg().setDlMotivoForzaAccettazione(this.getDlMotivoForzaAccettazione());
        entity.getOgg().setFlForzaWarning(this.getFlForzaWarning().equals(Constants.DB_TRUE));
        entity.getOgg().setDlMotivoChiusoWarning(this.getDlMotivoChiusoWarning());
        entity.getOgg().setCdErr(this.getCdErr());
        entity.getOgg().setDsErr(this.getDlErr());
        entity.getOgg().setTiStatoSessioneRecup(this.getTiStatoSessioneRecup());
        if (this.getDtAperturaSessioneRecup() != null) {
            cal.setTime(this.getDtAperturaSessioneRecup());
            entity.getOgg().setDtAperturaSessioneRecup(factory.newXMLGregorianCalendar(cal));
        } else {
            entity.getOgg().setDtAperturaSessioneRecup(null);
        }
        entity.getOgg().setChiaveUnitaDoc(this.getChiaveUnitaDoc());
        entity.setCdAetNodoDicom(this.getCdAetNodoDicom());
        entity.setDtStudyDate(this.getDtStudyDate());
        entity.setDsAccessionNumber(this.getDsAccessionNumber());
        entity.setDsPatientName(this.getDsPatientName());
        entity.setTiPatientSex(this.getTiPatientSex());
        entity.setDtPatientBirthDate(this.getDtPatientBirthDate());
        entity.setCdPatientId(this.getCdPatientId());
        entity.setCdPatientIdIssuer(this.getCdPatientIdIssuer());
        entity.setDsRefPhysicianName(this.getDsRefPhysicianName());
        entity.setDlListaModalityInStudy(this.getDlListaModalityInStudy());
        entity.setDlListaSopClass(this.getDlListaSopClass());
        entity.setDsInstitutionName(this.getDsInstitutionName());
        entity.setDlStudyDescription(this.getDlStudyDescription());
        entity.setDsStudyInstanceUid(this.getDsStudyInstanceUid());
        entity.setNiStudyRelatedSeries(this.getNiStudyRelatedSeries());
        entity.setNiStudyRelatedImages(this.getNiStudyRelatedImages());
        entity.setDsStudyId(this.getDsStudyId());
        entity.setDtPresaInCarico(this.getDtPresaInCarico());
        entity.setBlDcmHashTxt(this.getBlDcmHashTxt());
        entity.setDsDcmHash(this.getDsDcmHash());
        entity.setTiAlgoDcmHash(this.getTiAlgoDcmHash());
        entity.setCdEncodingDcmHash(this.getCdEncodingDcmHash());
        entity.setBlGlobalHashTxt(this.getBlGlobalHashTxt());
        entity.setDsGlobalHash(this.getDsGlobalHash());
        entity.setTiAlgoGlobalHash(this.getTiAlgoGlobalHash());
        entity.setCdEncodingGlobalHash(this.getCdEncodingGlobalHash());
        entity.setDsFileHash(this.getDsFileHash());
        entity.setTiAlgoFileHash(this.getTiAlgoFileHash());
        entity.setCdEncodingFileHash(this.getCdEncodingFileHash());
        return entity;
    }

    // gestione della paginazione
    public void setRownum(Integer rownum) {
        setObject("rownum", rownum);
    }

    public Integer getRownum() {
        return Integer.parseInt(getObject("rownum").toString());
    }

    public void setRnum(Integer rnum) {
        setObject("rnum", rnum);
    }

    public Integer getRnum() {
        return Integer.parseInt(getObject("rnum").toString());
    }

    public void setNumrecords(Integer numRecords) {
        setObject("numrecords", numRecords);
    }

    public Integer getNumrecords() {
        return Integer.parseInt(getObject("numrecords").toString());
    }

}
